<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <AssemblyName>UnityModelReplacement</AssemblyName>
    <Description>UnityModelReplacement</Description>
    <Version>1.0.0</Version>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="..\..\Unity Projects\R.E.P.O\Assets\AssetBundles\mods.bundle" Link="mods.bundle" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BepInEx.Analyzers" Version="1.*" PrivateAssets="all" />
    <PackageReference Include="BepInEx.Core" Version="5.*" />
    <PackageReference Include="BepInEx.PluginInfoProps" Version="1.*" />
    <PackageReference Include="UnityEngine.Modules" Version="2022.3.21" IncludeAssets="compile" />
  </ItemGroup>
  
  <ItemGroup Condition="'$(TargetFramework.TrimEnd(`0123456789`))' == 'net'">
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" PrivateAssets="all" />
  </ItemGroup>
  
  <ItemGroup>
    <Reference Include="Assembly-CSharp">
      <HintPath>..\..\Steam Library\steamapps\common\REPO\REPO_Data\Managed\Assembly-CSharp.dll</HintPath>
    </Reference>
    <Reference Include="netstandard">
      <HintPath>..\..\Steam Library\steamapps\common\REPO\REPO_Data\Managed\netstandard.dll</HintPath>
    </Reference>
  </ItemGroup>
  
  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="copy /Y &quot;$(TargetDir)$(ProjectName).dll&quot; &quot;F:\Steam Library\steamapps\common\REPO\BepInEx\plugins\$(ProjectName).dll&quot;" />
  </Target>
</Project>
