<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net46</TargetFramework>
    <AssemblyName>UnityModelReplacement</AssemblyName>
    <Description>Replacing models in My Friendly Neighborhood</Description>
    <Version>1.0.0</Version>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <LangVersion>latest</LangVersion>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <GamePath>F:\Steam Library\steamapps\common\My Friendly Neighborhood\</GamePath>
  </PropertyGroup>
  
  <PropertyGroup>
    <ReferencePath>$(ReferencePath);$(GamePath)\My Friendly Neighborhood_Data\Managed</ReferencePath>
    <ReferencePath>$(ReferencePath);$(GamePath)\My Friendly Neighborhood_Data\Plugins</ReferencePath>
    <ReferencePath>$(ReferencePath);$(GamePath)\BepInEx\plugins</ReferencePath>
    <RootNamespace>UnityModelReplacement</RootNamespace>
  </PropertyGroup>
  
  <ItemGroup>
    <None Remove="mods.bundle" />
  </ItemGroup>
  
  <ItemGroup>
    <EmbeddedResource Include="mods.bundle" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BepInEx.AssemblyPublicizer.MSBuild" Version="0.4.2" PrivateAssets="all" />
    <PackageReference Include="BepInEx.Analyzers" Version="1.*" PrivateAssets="all" />
    <PackageReference Include="BepInEx.Core" Version="5.*" IncludeAssets="compile" />
    <PackageReference Include="BepInEx.PluginInfoProps" Version="2.1.0" IncludeAssets="compile" />
    <PackageReference Include="HarmonyX" Version="2.13.0" />
    <PackageReference Include="UnityEngine.Modules" Version="6000.0.5">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework.TrimEnd(`0123456789`))' == 'net'">
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" PrivateAssets="all" />
  </ItemGroup>
  
  <ItemGroup>
    <Reference Include="Assembly-CSharp" Publicize="true">
      <HintPath>$(GamePath)\My Friendly Neighborhood_Data\Managed\Assembly-CSharp.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
  
  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
      <Exec Command="copy /Y &quot;$(TargetDir)$(ProjectName).dll&quot; &quot;$(GamePath)BepInEx\plugins\$(ProjectName).dll&quot; &#xD;&#xA;" />
  </Target>
</Project>
